Samples/NET/cs/ProjectTracker/Mvc3UI/Controllers/ResourceAssignmentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ProjectTracker.Library;

namespace Mvc3UI.Controllers
{
  [Csla.Web.Mvc.HasPermission(Csla.Rules.AuthorizationActions.EditObject, typeof(ResourceEdit))]
  public class ResourceAssignmentController : Controller
  {
    //
    // GET: /ResourceAssignment/

    public ActionResult Index(int id)
    {
      var resource = ResourceEdit.GetResource(id);
      ViewData.Add("ResourceId", resource.Id);
      ViewData.Add("Title", resource.FullName);
      ViewData.Model = resource.Assignments;
      return View();
    }

    //
    // GET: /ResourceAssignment/Create

    public ActionResult Create(int resourceId)
    {
      ViewData.Add("ResourceId", resourceId);
      return View();
    }

    //
    // POST: /ResourceAssignment/Create

    [HttpPost]
    public ActionResult Create(int resourceId, FormCollection collection)
    {
      try
      {
        var resource = ResourceEdit.GetResource(resourceId);
        var projectId = int.Parse(collection["ProjectId"]);
        var model = resource.Assignments.AssignTo(projectId);
        model.Role = int.Parse(collection["Role"]);
        resource = resource.Save();
        return RedirectToAction("Index", new { id = resource.Id });
      }
      catch (Exception ex)
      {
        ViewData.Add("Error", ex);
        ViewData.Add("ProjectId", resourceId);
        ViewData.Model = new ResourceAssignmentEdit();
        return View();
      }
    }

    //
    // GET: /ResourceAssignment/Edit/5

    public ActionResult Edit(int projectId, int resourceId)
    {
      var resource = ResourceEdit.GetResource(resourceId);
      ViewData.Add("ResourceId", resource.Id);
      ViewData.Model = resource.Assignments.Where(r => r.ProjectId == projectId).First();
      return View();
    }

    //
    // POST: /ResourceAssignment/Edit/5

    [HttpPost]
    public ActionResult Edit(int projectId, int resourceId, FormCollection collection)
    {
      var resource = ResourceEdit.GetResource(resourceId);
      var model = resource.Assignments.Where(r => r.ProjectId == projectId).First();
      try
      {
        model.Role = int.Parse(collection["Role"]);
        resource = resource.Save();
        return RedirectToAction("Index", new { id = resource.Id });
      }
      catch
      {
        ViewData.Add("ResourceId", resource.Id);
        ViewData.Model = resource.Assignments.Where(r => r.ProjectId == projectId).First();
        return View();
      }
    }

    //
    // GET: /ResourceAssignment/Delete/5

    public ActionResult Delete(int projectId, int resourceId)
    {
      var resource = ResourceEdit.GetResource(resourceId);
      ViewData.Add("ResourceId", resource.Id);
      ViewData.Model = resource.Assignments.Where(r => r.ProjectId == projectId).First();
      return View();
    }

    //
    // POST: /ResourceAssignment/Delete/5

    [HttpPost]
    public ActionResult Delete(int projectId, int resourceId, FormCollection collection)
    {
      var resource = ResourceEdit.GetResource(resourceId);
      var model = resource.Assignments.Where(r => r.ProjectId == projectId).First();
      try
      {
        resource.Assignments.Remove(model);
        resource = resource.Save();
        return RedirectToAction("Index", new { id = resource.Id });
      }
      catch
      {
        ViewData.Add("ResourceId", resource.Id);
        ViewData.Model = resource.Assignments.Where(r => r.ProjectId == projectId).First();
        return View();
      }
    }
  }
}

Samples/NET/cs/ProjectTracker/Mvc3UI/Controllers/ResourceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ProjectTracker.Library;
using Mvc3UI.ViewModels;

namespace Mvc3UI.Controllers
{
  public class ResourceController : Csla.Web.Mvc.Controller
  {
    //
    // GET: /Resource/

    public ActionResult Index()
    {
      ViewData.Model = ResourceList.GetResourceList();
      return View();
    }

    //
    // GET: /Resource/Details/5

    [Csla.Web.Mvc.HasPermission(Csla.Rules.AuthorizationActions.GetObject, typeof(ResourceEdit))]
    public ActionResult Details(int id)
    {
      ViewData.Model = new ResourceViewModel(id);
      return View();
    }

    //
    // GET: /Resource/Create

    [Csla.Web.Mvc.HasPermission(Csla.Rules.AuthorizationActions.CreateObject, typeof(ResourceEdit))]
    public ActionResult Create()
    {
      ViewData.Model = new ResourceViewModel();
      return View();
    }

    //
    // POST: /Resource/Create

    [HttpPost]
    [Csla.Web.Mvc.HasPermission(Csla.Rules.AuthorizationActions.CreateObject, typeof(ResourceEdit))]
    public ActionResult Create(ResourceViewModel resource)
    {
      if (resource.Save(ModelState, false))
      {
        return RedirectToAction("Index", new { id = resource.ModelObject.Id });
      }
      else
      {
        ViewData.Model = resource;
        return View();
      }
    }

    //
    // GET: /Resource/Edit/5

    [Csla.Web.Mvc.HasPermission(Csla.Rules.AuthorizationActions.EditObject, typeof(ResourceEdit))]
    public ActionResult Edit(int id)
    {
      ViewData.Model = new ResourceViewModel(id);
      return View();
    }

    //
    // POST: /Resource/Edit/5

    [HttpPost]
    [Csla.Web.Mvc.HasPermission(Csla.Rules.AuthorizationActions.EditObject, typeof(ResourceEdit))]
    public ActionResult Edit(int id, ResourceViewModel resource)
    {
      if (resource.Save(ModelState, true))
      {
        return RedirectToAction("Index", new { id = resource.ModelObject.Id });
      }
      else
      {
        ViewData.Model = resource;
        return View();
      }
    }

    //
    // GET: /Resource/Delete/5

    [Csla.Web.Mvc.HasPermission(Csla.Rules.AuthorizationActions.DeleteObject, typeof(ResourceEdit))]
    public ActionResult Delete(int id)
    {
      ViewData.Model = new ResourceViewModel(id);
      return View();
    }

    //
    // POST: /Resource/Delete/5

    [HttpPost]
    [Csla.Web.Mvc.HasPermission(Csla.Rules.AuthorizationActions.DeleteObject, typeof(ResourceEdit))]
    public ActionResult Delete(int id, FormCollection collection)
    {
      try
      {
        ResourceEdit.DeleteResource(id);
        return RedirectToAction("Index");
      }
      catch
      {
        ViewData.Model = ResourceEdit.GetResource(id);
        return View();
      }
    }
  }
}

Samples/NET/cs/ProjectTracker/Mvc3UI/Views/ResourceAssignment/Create.cshtml
@{
    ViewBag.Title = "Assign to project";
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm()) {
  if (ViewData["Error"] != null) {
    var error = (Exception)ViewData["Error"];
    <div class="error">
      @error.Message
    </div>
    <br />
  }

      <fieldset>
        <legend>Resource Assignment</legend>

    <div class="editor-label">
      Role
    </div>
    <div class="editor-field">
      @Html.DropDownList("Role", new SelectList(ProjectTracker.Library.RoleList.GetList(), "Key", "Value"))
    </div>

    <div class="editor-label">
      Project
    </div>
    <div class="editor-field">
      @Html.DropDownList("ProjectId", new SelectList(ProjectTracker.Library.ProjectList.GetProjectList(), "Id", "Name"))
    </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
  @Html.ActionLink("Back to List", "Index", new { id = ViewData["ResourceId"] })
</div>

Samples/NET/cs/ProjectTracker/Mvc3UI/Views/ResourceAssignment/Delete.cshtml
@model ProjectTracker.Library.ResourceAssignmentEdit

@{
    ViewBag.Title = "Remove from project";
}

<h2>@ViewBag.Title</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>Resource Assignment</legend>

    <div class="display-label">Project</div>
    <div class="display-field">@Model.ProjectName</div>

    <div class="display-label">Assigned</div>
    <div class="display-field">@Model.Assigned</div>

    <div class="display-label">Role</div>
    <div class="display-field">@Model.RoleName</div>

</fieldset>
@using (Html.BeginForm()) {
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index", new { resourceId = ViewData["ResourceId"], projectId = Model.ProjectId })
    </p>
}

Samples/NET/cs/ProjectTracker/Mvc3UI/Views/ResourceAssignment/Edit.cshtml
@model ProjectTracker.Library.ResourceAssignmentEdit

@{
    ViewBag.Title = "Edit assignment";
}

<h2>@ViewBag.Title</h2>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>ResourceAssignmentEdit</legend>

    <div class="editor-label">
      @Html.LabelFor(model => model.Role)
    </div>
    <div class="editor-field">
      @Html.DropDownListFor(model => model.Role, new SelectList(ProjectTracker.Library.RoleList.GetList(), "Key", "Value"))
    </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
  @Html.ActionLink("Back to List", "Index", new { id = ViewData["ResourceId"] })
</div>

Samples/NET/cs/ProjectTracker/Mvc3UI/Views/ResourceAssignment/Index.cshtml
@model IEnumerable<ProjectTracker.Library.ResourceAssignmentEdit>

@{
  ViewBag.Title = "Assignments for " + @ViewData["Title"];
}

<h2>@ViewBag.Title</h2>

<p>
    @Html.ActionLink("Add New", "Create", new { resourceId = ViewData["ResourceId"] })
</p>
<table>
    <tr>
        <th></th>
        <th>
            Project
        </th>
        <th>
            Assigned
        </th>
        <th>
            Role
        </th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.ActionLink("Edit", "Edit", new { projectId = item.ProjectId, resourceId = ViewData["ResourceId"] }) |
            @Html.ActionLink("Delete", "Delete", new { projectId = item.ProjectId, resourceId = ViewData["ResourceId"] })
        </td>
        <td>
            @item.ProjectName
        </td>
        <td>
            @item.Assigned
        </td>
        <td>
            @item.RoleName
        </td>
    </tr>
}

</table>
<div>
  @Html.ActionLink("Back to Resource", "Edit", "Resource", new { id = ViewData["ResourceId"] }, null)
</div>