Samples/NET/cs/ProjectTracker/Mvc3UI/Controllers/ProjectController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ProjectTracker.Library;

namespace Mvc3UI.Controllers
{
  public class ProjectController : Csla.Web.Mvc.Controller, Csla.Web.Mvc.IModelCreator
  {
    public object CreateModel(Type modelType)
    {
      // this CreateModel method is entirely optional, and
      // exists to demonstrate how you implement the
      // IModelCreator interface
      if (modelType.Equals(typeof(ProjectEdit)))
        return ProjectEdit.NewProject();
      else
        return Activator.CreateInstance(modelType);
    }

    //
    // GET: /Project/

    public ActionResult Index()
    {
      ViewData.Model = ProjectList.GetProjectList();
      return View();
    }

    //
    // GET: /Project/Details/5

    [Csla.Web.Mvc.HasPermission(Csla.Rules.AuthorizationActions.GetObject, typeof(ProjectEdit))]
    public ActionResult Details(int id)
    {
      ViewData.Model = ProjectEdit.GetProject(id);
      return View();
    }

    //
    // GET: /Project/Create

    [Csla.Web.Mvc.HasPermission(Csla.Rules.AuthorizationActions.CreateObject, typeof(ProjectEdit))]
    public ActionResult Create()
    {
      ViewData.Model = ProjectEdit.NewProject();
      return View();
    }

    //
    // POST: /Project/Create

    [HttpPost]
    [Csla.Web.Mvc.HasPermission(Csla.Rules.AuthorizationActions.CreateObject, typeof(ProjectEdit))]
    public ActionResult Create(ProjectEdit project)
    {
      if (SaveObject(project, false))
        return RedirectToAction("Index", new { id = project.Id });
      else
        return View();
    }

    //
    // GET: /Project/Edit/5

    [Csla.Web.Mvc.HasPermission(Csla.Rules.AuthorizationActions.EditObject, typeof(ProjectEdit))]
    public ActionResult Edit(int id)
    {
      ViewData.Model = ProjectEdit.GetProject(id);
      return View();
    }

    //
    // POST: /Project/Edit/5

    [HttpPost]
    [Csla.Web.Mvc.HasPermission(Csla.Rules.AuthorizationActions.EditObject, typeof(ProjectEdit))]
    public ActionResult Edit(int id, ProjectEdit project)
    {
      LoadProperty(project, ProjectEdit.IdProperty, id);
      if (SaveObject(project, true))
        return RedirectToAction("Index");
      else
        return View();
    }

    //
    // GET: /Project/Delete/5

    [Csla.Web.Mvc.HasPermission(Csla.Rules.AuthorizationActions.DeleteObject, typeof(ProjectEdit))]
    public ActionResult Delete(int id)
    {
      ViewData.Model = ProjectEdit.GetProject(id);
      return View();
    }

    //
    // POST: /Project/Delete/5

    [HttpPost]
    [Csla.Web.Mvc.HasPermission(Csla.Rules.AuthorizationActions.DeleteObject, typeof(ProjectEdit))]
    public ActionResult Delete(int id, FormCollection collection)
    {
      try
      {
        ProjectEdit.DeleteProject(id);
        return RedirectToAction("Index");
      }
      catch (Exception ex)
      {
        ViewData.Model = ProjectEdit.GetProject(id);
        ModelState.AddModelError("", ex.Message);
        return View();
      }
    }
  }
}

Samples/NET/cs/ProjectTracker/Mvc3UI/Controllers/ResourceAssignmentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ProjectTracker.Library;

namespace Mvc3UI.Controllers
{
  [Csla.Web.Mvc.HasPermission(Csla.Rules.AuthorizationActions.EditObject, typeof(ResourceEdit))]
  public class ResourceAssignmentController : Controller
  {
    //
    // GET: /ResourceAssignment/

    public ActionResult Index(int id)
    {
      var resource = ResourceEdit.GetResource(id);
      ViewData.Add("ResourceId", resource.Id);
      ViewData.Add("Title", resource.FullName);
      ViewData.Model = resource.Assignments;
      return View();
    }

    //
    // GET: /ResourceAssignment/Create

    public ActionResult Create(int resourceId)
    {
      ViewData.Add("ResourceId", resourceId);
      return View();
    }

    //
    // POST: /ResourceAssignment/Create

    [HttpPost]
    public ActionResult Create(int resourceId, FormCollection collection)
    {
      try
      {
        var resource = ResourceEdit.GetResource(resourceId);
        var projectId = int.Parse(collection["ProjectId"]);
        var model = resource.Assignments.AssignTo(projectId);
        model.Role = int.Parse(collection["Role"]);
        resource = resource.Save();
        return RedirectToAction("Index", new { id = resource.Id });
      }
      catch (Exception ex)
      {
        ViewData.Add("Error", ex);
        ViewData.Add("ProjectId", resourceId);
        ViewData.Model = new ResourceAssignmentEdit();
        return View();
      }
    }

    //
    // GET: /ResourceAssignment/Edit/5

    public ActionResult Edit(int projectId, int resourceId)
    {
      var resource = ResourceEdit.GetResource(resourceId);
      ViewData.Add("ResourceId", resource.Id);
      ViewData.Model = resource.Assignments.Where(r => r.ProjectId == projectId).First();
      return View();
    }

    //
    // POST: /ResourceAssignment/Edit/5

    [HttpPost]
    public ActionResult Edit(int projectId, int resourceId, FormCollection collection)
    {
      var resource = ResourceEdit.GetResource(resourceId);
      var model = resource.Assignments.Where(r => r.ProjectId == projectId).First();
      try
      {
        model.Role = int.Parse(collection["Role"]);
        resource = resource.Save();
        return RedirectToAction("Index", new { id = resource.Id });
      }
      catch
      {
        ViewData.Add("ResourceId", resource.Id);
        ViewData.Model = resource.Assignments.Where(r => r.ProjectId == projectId).First();
        return View();
      }
    }

    //
    // GET: /ResourceAssignment/Delete/5

    public ActionResult Delete(int projectId, int resourceId)
    {
      var resource = ResourceEdit.GetResource(resourceId);
      ViewData.Add("ResourceId", resource.Id);
      ViewData.Model = resource.Assignments.Where(r => r.ProjectId == projectId).First();
      return View();
    }

    //
    // POST: /ResourceAssignment/Delete/5

    [HttpPost]
    public ActionResult Delete(int projectId, int resourceId, FormCollection collection)
    {
      var resource = ResourceEdit.GetResource(resourceId);
      var model = resource.Assignments.Where(r => r.ProjectId == projectId).First();
      try
      {
        resource.Assignments.Remove(model);
        resource = resource.Save();
        return RedirectToAction("Index", new { id = resource.Id });
      }
      catch
      {
        ViewData.Add("ResourceId", resource.Id);
        ViewData.Model = resource.Assignments.Where(r => r.ProjectId == projectId).First();
        return View();
      }
    }
  }
}

Samples/NET/cs/ProjectTracker/Mvc3UI/Views/Resource/Create.cshtml
@model Mvc3UI.ViewModels.ResourceViewModel

@{
    ViewBag.Title = "Create resource";
}

<h2>@ViewBag.Title</h2>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>Resource</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.ModelObject.FirstName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.ModelObject.FirstName)
            @Html.ValidationMessageFor(model => model.ModelObject.FirstName)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.ModelObject.LastName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.ModelObject.LastName)
            @Html.ValidationMessageFor(model => model.ModelObject.LastName)
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Samples/NET/cs/ProjectTracker/Mvc3UI/Views/Resource/Delete.cshtml
@model Mvc3UI.ViewModels.ResourceViewModel

@{
    ViewBag.Title = "Delete resource";
}

<h2>@ViewBag.Title</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>Resource</legend>

    <div class="display-label">Name</div>
    <div class="display-field">@Model.ModelObject.FullName</div>

</fieldset>
@using (Html.BeginForm()) {
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

Samples/NET/cs/ProjectTracker/Mvc3UI/Views/Resource/Details.cshtml
@using Csla.Web.Mvc
@using ProjectTracker.Library

@model Mvc3UI.ViewModels.ResourceViewModel

@{
    ViewBag.Title = "Resource details";
}

<h2>@ViewBag.Title</h2>

<fieldset>
    <legend>Resource</legend>

    <div class="display-label">FirstName</div>
    <div class="display-field">@Model.ModelObject.FirstName</div>

    <div class="display-label">LastName</div>
    <div class="display-field">@Model.ModelObject.LastName</div>

    <div class="display-label">FullName</div>
    <div class="display-field">@Model.ModelObject.FullName</div>

</fieldset>

<div>
<div class="display-label">Project assignments</div>
<table>
<thead>
  <tr><td>Project</td><td>Assigned</td><td>Role</td></tr>
</thead>
<tbody>
@foreach (var item in Model.ModelObject.Assignments) { 
  <tr><td>@Html.ActionLink(item.ProjectName, "Details", "Project", new { id = item.ProjectId }, null)</td><td>@String.Format("{0:d}", item.Assigned)</td><td>@item.RoleName</td></tr>
}
</tbody></table>
</div>
<br />

<p>
    @Html.HasPermission(Csla.Rules.AuthorizationActions.EditObject, typeof(ResourceEdit), Html.ActionLink("Edit", "Edit", new { id = Model.ModelObject.Id }), "Edit") |
    @Html.ActionLink("Back to List", "Index")
</p>

Samples/NET/cs/ProjectTracker/Mvc3UI/Views/Resource/Edit.cshtml
@model Mvc3UI.ViewModels.ResourceViewModel

@{
    ViewBag.Title = "Edit resource";
}

<h2>@ViewBag.Title</h2>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>Resource</legend>

        @Html.HiddenFor(model => model.ModelObject.Id)
        @Html.HiddenFor(model => model.ModelObject.TimeStamp)

        <div class="editor-label">
            @Html.LabelFor(model => model.ModelObject.FirstName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.ModelObject.FirstName)
            @Html.ValidationMessageFor(model => model.ModelObject.FirstName)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.ModelObject.LastName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.ModelObject.LastName)
            @Html.ValidationMessageFor(model => model.ModelObject.LastName)
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>

    <fieldset>
      <legend>Assignments</legend>
      <table>
        <thead>
          <tr>
            <td>
              Project
            </td>
            <td>
              Assigned
            </td>
            <td>
              Role
            </td>
          </tr>
        </thead>
        <tbody>
          @foreach (var item in Model.ModelObject.Assignments)
          { 
            <tr>
              <td>@item.ProjectName
              </td>
              <td>@String.Format("{0:d}", item.Assigned)
              </td>
              <td>@item.RoleName
              </td>
            </tr>
          }
        </tbody>
      </table>
      @Html.ActionLink("Edit assignments", "Index", "ResourceAssignment", new { id = Model.ModelObject.Id }, null)
    </fieldset>
  </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Samples/NET/cs/ProjectTracker/Mvc3UI/Views/Resource/Index.cshtml
@using Csla.Web.Mvc
@using ProjectTracker.Library

@model IEnumerable<ProjectTracker.Library.ResourceInfo>

@{
    ViewBag.Title = "Resources";
}

<h2>@ViewBag.Title</h2>

<p>
   @Html.HasPermission(Csla.Rules.AuthorizationActions.CreateObject, typeof(ResourceEdit), Html.ActionLink("Create New", "Create"), string.Empty)
</p>
<table>
    <tr>
        <th></th>
        <th>
            Name
        </th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.HasPermission(Csla.Rules.AuthorizationActions.EditObject, typeof(ResourceEdit), Html.ActionLink("Edit", "Edit", new { id = item.Id }), "Edit") |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.HasPermission(Csla.Rules.AuthorizationActions.DeleteObject, typeof(ResourceEdit), Html.ActionLink("Delete", "Delete", new { id = item.Id }), "Delete")
        </td>
        <td>
            @item.Name
        </td>
    </tr>
}

</table>